//------------------------------------------------------------------------------
// <auto-generated>
//     Il codice è stato generato da uno strumento.
//     Versione runtime:4.0.30319.42000
//
//     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SysInfo {
    using System;
    
    
    /// <summary>
    ///   Classe di risorse fortemente tipizzata per la ricerca di stringhe localizzate e così via.
    /// </summary>
    // Questa classe è stata generata automaticamente dalla classe StronglyTypedResourceBuilder.
    // tramite uno strumento quale ResGen o Visual Studio.
    // Per aggiungere o rimuovere un membro, modificare il file con estensione ResX ed eseguire nuovamente ResGen
    // con l'opzione /str oppure ricompilare il progetto VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class be_local {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal be_local() {
        }
        
        /// <summary>
        ///   Restituisce l'istanza di ResourceManager nella cache utilizzata da questa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SysInfo.be_local", typeof(be_local).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Esegue l'override della proprietà CurrentUICulture del thread corrente per tutte le
        ///   ricerche di risorse eseguite utilizzando questa classe di risorse fortemente tipizzata.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a ?.
        /// </summary>
        internal static string _help {
            get {
                return ResourceManager.GetString("_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a інтэрфейс.
        /// </summary>
        internal static string _interface {
            get {
                return ResourceManager.GetString("_interface", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Аб SysInfo.
        /// </summary>
        internal static string about {
            get {
                return ResourceManager.GetString("about", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a рахункі.
        /// </summary>
        internal static string accounts {
            get {
                return ResourceManager.GetString("accounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a акумулятар.
        /// </summary>
        internal static string battery {
            get {
                return ResourceManager.GetString("battery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a BIOS.
        /// </summary>
        internal static string bios {
            get {
                return ResourceManager.GetString("bios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a магутнасць.
        /// </summary>
        internal static string capacity {
            get {
                return ResourceManager.GetString("capacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a кампутар.
        /// </summary>
        internal static string computer {
            get {
                return ResourceManager.GetString("computer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a парты падключэння.
        /// </summary>
        internal static string connection_ports {
            get {
                return ResourceManager.GetString("connection_ports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a стрыжні.
        /// </summary>
        internal static string cores {
            get {
                return ResourceManager.GetString("cores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Цэнтральны працэсар.
        /// </summary>
        internal static string cpu {
            get {
                return ResourceManager.GetString("cpu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a каталог.
        /// </summary>
        internal static string directory {
            get {
                return ResourceManager.GetString("directory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a раздзелы дыска.
        /// </summary>
        internal static string disk_partitions {
            get {
                return ResourceManager.GetString("disk_partitions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Дата драйвера.
        /// </summary>
        internal static string driver_date {
            get {
                return ResourceManager.GetString("driver_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a версія драйвера.
        /// </summary>
        internal static string driver_version {
            get {
                return ResourceManager.GetString("driver_version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a зменныя асяроддзя.
        /// </summary>
        internal static string environment_variables {
            get {
                return ResourceManager.GetString("environment_variables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Выхад з SysInfo ....
        /// </summary>
        internal static string exit {
            get {
                return ResourceManager.GetString("exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a файл.
        /// </summary>
        internal static string file {
            get {
                return ResourceManager.GetString("file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a поўная зарадка.
        /// </summary>
        internal static string full_charge {
            get {
                return ResourceManager.GetString("full_charge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a жорсткія дыскі.
        /// </summary>
        internal static string hard_disks {
            get {
                return ResourceManager.GetString("hard_disks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a інфармацыя.
        /// </summary>
        internal static string informations {
            get {
                return ResourceManager.GetString("informations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Устаноўленая.
        /// </summary>
        internal static string installed {
            get {
                return ResourceManager.GetString("installed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a устаноўленыя кодэк.
        /// </summary>
        internal static string installed_codecs {
            get {
                return ResourceManager.GetString("installed_codecs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Bielorusian.
        /// </summary>
        internal static string LANGUAGE {
            get {
                return ResourceManager.GetString("LANGUAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a ліст.
        /// </summary>
        internal static string letter {
            get {
                return ResourceManager.GetString("letter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a ліцэнзія.
        /// </summary>
        internal static string license {
            get {
                return ResourceManager.GetString("license", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a лагічныя дыскі.
        /// </summary>
        internal static string logical_disks {
            get {
                return ResourceManager.GetString("logical_disks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a вытворца.
        /// </summary>
        internal static string manufacturer {
            get {
                return ResourceManager.GetString("manufacturer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a максімальна даступная.
        /// </summary>
        internal static string max_available {
            get {
                return ResourceManager.GetString("max_available", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a мадэль.
        /// </summary>
        internal static string model {
            get {
                return ResourceManager.GetString("model", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a матчына плата.
        /// </summary>
        internal static string motherboard {
            get {
                return ResourceManager.GetString("motherboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a імя.
        /// </summary>
        internal static string name {
            get {
                return ResourceManager.GetString("name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a сеткавыя адаптары.
        /// </summary>
        internal static string network_adapters {
            get {
                return ResourceManager.GetString("network_adapters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a добра.
        /// </summary>
        internal static string ok {
            get {
                return ResourceManager.GetString("ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Аперацыйная сістэма.
        /// </summary>
        internal static string operating_system {
            get {
                return ResourceManager.GetString("operating_system", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a аптычныя прывады.
        /// </summary>
        internal static string optical_drives {
            get {
                return ResourceManager.GetString("optical_drives", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Націсніце для атрымання больш падрабязнай інфармацыі..
        /// </summary>
        internal static string press_buttons {
            get {
                return ResourceManager.GetString("press_buttons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a паведамленні ў прэсе.
        /// </summary>
        internal static string print_report {
            get {
                return ResourceManager.GetString("print_report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a прынтэры.
        /// </summary>
        internal static string printers {
            get {
                return ResourceManager.GetString("printers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a RAM.
        /// </summary>
        internal static string ram {
            get {
                return ResourceManager.GetString("ram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a намінальны Charge.
        /// </summary>
        internal static string rated_charge {
            get {
                return ResourceManager.GetString("rated_charge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a агульныя прынтэры.
        /// </summary>
        internal static string shared_printers {
            get {
                return ResourceManager.GetString("shared_printers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a гульнявыя аўтаматы.
        /// </summary>
        internal static string slots {
            get {
                return ResourceManager.GetString("slots", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a разетка.
        /// </summary>
        internal static string socket {
            get {
                return ResourceManager.GetString("socket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a гукавыя прылады.
        /// </summary>
        internal static string sound_devices {
            get {
                return ResourceManager.GetString("sound_devices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a статус.
        /// </summary>
        internal static string status {
            get {
                return ResourceManager.GetString("status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a тып сістэмы.
        /// </summary>
        internal static string system_type {
            get {
                return ResourceManager.GetString("system_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a тып.
        /// </summary>
        internal static string type {
            get {
                return ResourceManager.GetString("type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a значэнне.
        /// </summary>
        internal static string value {
            get {
                return ResourceManager.GetString("value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a версія.
        /// </summary>
        internal static string version {
            get {
                return ResourceManager.GetString("version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a відэа.
        /// </summary>
        internal static string video {
            get {
                return ResourceManager.GetString("video", resourceCulture);
            }
        }
    }
}
