//------------------------------------------------------------------------------
// <auto-generated>
//     Il codice è stato generato da uno strumento.
//     Versione runtime:4.0.30319.42000
//
//     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SysInfo {
    using System;
    
    
    /// <summary>
    ///   Classe di risorse fortemente tipizzata per la ricerca di stringhe localizzate e così via.
    /// </summary>
    // Questa classe è stata generata automaticamente dalla classe StronglyTypedResourceBuilder.
    // tramite uno strumento quale ResGen o Visual Studio.
    // Per aggiungere o rimuovere un membro, modificare il file con estensione ResX ed eseguire nuovamente ResGen
    // con l'opzione /str oppure ricompilare il progetto VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class cz_local {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal cz_local() {
        }
        
        /// <summary>
        ///   Restituisce l'istanza di ResourceManager nella cache utilizzata da questa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SysInfo.cz_local", typeof(cz_local).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Esegue l'override della proprietà CurrentUICulture del thread corrente per tutte le
        ///   ricerche di risorse eseguite utilizzando questa classe di risorse fortemente tipizzata.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a ?.
        /// </summary>
        internal static string _help {
            get {
                return ResourceManager.GetString("_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Rozhraní.
        /// </summary>
        internal static string _interface {
            get {
                return ResourceManager.GetString("_interface", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a O společnosti SysInfo.
        /// </summary>
        internal static string about {
            get {
                return ResourceManager.GetString("about", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Účty.
        /// </summary>
        internal static string accounts {
            get {
                return ResourceManager.GetString("accounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a baterie.
        /// </summary>
        internal static string battery {
            get {
                return ResourceManager.GetString("battery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a BIOS.
        /// </summary>
        internal static string bios {
            get {
                return ResourceManager.GetString("bios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Kapacita.
        /// </summary>
        internal static string capacity {
            get {
                return ResourceManager.GetString("capacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Počítač.
        /// </summary>
        internal static string computer {
            get {
                return ResourceManager.GetString("computer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Připojovací porty.
        /// </summary>
        internal static string connection_ports {
            get {
                return ResourceManager.GetString("connection_ports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Jádra.
        /// </summary>
        internal static string cores {
            get {
                return ResourceManager.GetString("cores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a procesor.
        /// </summary>
        internal static string cpu {
            get {
                return ResourceManager.GetString("cpu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Adresář.
        /// </summary>
        internal static string directory {
            get {
                return ResourceManager.GetString("directory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Diskové oddíly.
        /// </summary>
        internal static string disk_partitions {
            get {
                return ResourceManager.GetString("disk_partitions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Datum řidiče.
        /// </summary>
        internal static string driver_date {
            get {
                return ResourceManager.GetString("driver_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Verze ovladače.
        /// </summary>
        internal static string driver_version {
            get {
                return ResourceManager.GetString("driver_version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;root&gt;
        ///  &lt;!-- 
        ///    Microsoft ResX Schema 
        ///    
        ///    Version 2.0
        ///    
        ///    The primary goals of this format is to allow a simple XML format 
        ///    that is mostly human readable. The generation and parsing of the 
        ///    various data types are done through the TypeConverter classes 
        ///    associated with the data types.
        ///    
        ///    Example:
        ///    
        ///    ... ado.net/XML headers &amp; schema ...
        ///    &lt;resheader name=&quot;resmimetype&quot;&gt;text/microsoft-resx&lt;/resheader&gt;
        ///    &lt;resheader n [stringa troncata]&quot;;.
        /// </summary>
        internal static string en_local {
            get {
                return ResourceManager.GetString("en_local", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a //------------------------------------------------------------------------------
        ///// &lt;auto-generated&gt;
        /////     Il codice è stato generato da uno strumento.
        /////     Versione runtime:4.0.30319.42000
        /////
        /////     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
        /////     il codice viene rigenerato.
        ///// &lt;/auto-generated&gt;
        /////------------------------------------------------------------------------------
        ///
        ///namespace SysInfo {
        ///    using System;
        ///    
        ///    
        ///     [stringa troncata]&quot;;.
        /// </summary>
        internal static string en_local_Designer {
            get {
                return ResourceManager.GetString("en_local_Designer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Proměnné prostředí.
        /// </summary>
        internal static string environment_variables {
            get {
                return ResourceManager.GetString("environment_variables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Ukončit ze systému SysInfo ....
        /// </summary>
        internal static string exit {
            get {
                return ResourceManager.GetString("exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Soubor.
        /// </summary>
        internal static string file {
            get {
                return ResourceManager.GetString("file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Plné nabití.
        /// </summary>
        internal static string full_charge {
            get {
                return ResourceManager.GetString("full_charge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Pevné disky.
        /// </summary>
        internal static string hard_disks {
            get {
                return ResourceManager.GetString("hard_disks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Informace.
        /// </summary>
        internal static string informations {
            get {
                return ResourceManager.GetString("informations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Instalováno.
        /// </summary>
        internal static string installed {
            get {
                return ResourceManager.GetString("installed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Instalované kodeky.
        /// </summary>
        internal static string installed_codecs {
            get {
                return ResourceManager.GetString("installed_codecs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Czech.
        /// </summary>
        internal static string LANGUAGE {
            get {
                return ResourceManager.GetString("LANGUAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Dopis.
        /// </summary>
        internal static string letter {
            get {
                return ResourceManager.GetString("letter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Licence.
        /// </summary>
        internal static string license {
            get {
                return ResourceManager.GetString("license", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Logické disky.
        /// </summary>
        internal static string logical_disks {
            get {
                return ResourceManager.GetString("logical_disks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Výrobce.
        /// </summary>
        internal static string manufacturer {
            get {
                return ResourceManager.GetString("manufacturer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Maximálně k dispozici.
        /// </summary>
        internal static string max_available {
            get {
                return ResourceManager.GetString("max_available", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Modelka.
        /// </summary>
        internal static string model {
            get {
                return ResourceManager.GetString("model", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Základní deska.
        /// </summary>
        internal static string motherboard {
            get {
                return ResourceManager.GetString("motherboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a název.
        /// </summary>
        internal static string name {
            get {
                return ResourceManager.GetString("name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Síťové adaptéry.
        /// </summary>
        internal static string network_adapters {
            get {
                return ResourceManager.GetString("network_adapters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a OK.
        /// </summary>
        internal static string ok {
            get {
                return ResourceManager.GetString("ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Operační systém.
        /// </summary>
        internal static string operating_system {
            get {
                return ResourceManager.GetString("operating_system", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Optické mechaniky.
        /// </summary>
        internal static string optical_drives {
            get {
                return ResourceManager.GetString("optical_drives", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Stiskněte pro podrobnější informace..
        /// </summary>
        internal static string press_buttons {
            get {
                return ResourceManager.GetString("press_buttons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Tiskárny.
        /// </summary>
        internal static string printers {
            get {
                return ResourceManager.GetString("printers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a RAM.
        /// </summary>
        internal static string ram {
            get {
                return ResourceManager.GetString("ram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Rated Charge.
        /// </summary>
        internal static string rated_charge {
            get {
                return ResourceManager.GetString("rated_charge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Sdílené tiskárny.
        /// </summary>
        internal static string shared_printers {
            get {
                return ResourceManager.GetString("shared_printers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Sloty.
        /// </summary>
        internal static string slots {
            get {
                return ResourceManager.GetString("slots", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Zásuvka.
        /// </summary>
        internal static string socket {
            get {
                return ResourceManager.GetString("socket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Zvuková zařízení.
        /// </summary>
        internal static string sound_devices {
            get {
                return ResourceManager.GetString("sound_devices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Postavení.
        /// </summary>
        internal static string status {
            get {
                return ResourceManager.GetString("status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Tisková Zpráva.
        /// </summary>
        internal static string String1 {
            get {
                return ResourceManager.GetString("String1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Typ systému.
        /// </summary>
        internal static string system_type {
            get {
                return ResourceManager.GetString("system_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Typ.
        /// </summary>
        internal static string type {
            get {
                return ResourceManager.GetString("type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Hodnota.
        /// </summary>
        internal static string value {
            get {
                return ResourceManager.GetString("value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Verze.
        /// </summary>
        internal static string version {
            get {
                return ResourceManager.GetString("version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Video.
        /// </summary>
        internal static string video {
            get {
                return ResourceManager.GetString("video", resourceCulture);
            }
        }
    }
}
